### ISSUE TITLE
php artisan migrate --seed --force reports an error

### ISSUE THREAD

**Issue by devilAPI** [Jexactyl/Jexactyl-v2-Archive#21]
### Current Behavior

![image](https://user-images.githubusercontent.com/52862870/155603812-9f2c6ad9-86e5-4d58-a650-8b96f978b72c.png)

### Expected Behavior

The command should run without problems and the panel should be up.

### Steps to Reproduce

run the command (?)

### Panel Version

latest

### Wings Version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Have you tried rolling back the database before you try and migrate it?

Before you complete any of these steps, back up your database:
```mysqldump panel > /root/backup.sql```

Then, try running the following commands to successfully migrate your database.
```php artisan migrate:rollback```
Then:
```php artisan migrate --seed --force```

If there is an error, please post it here - if not, let me know!

**Comment by devilAPI** [comment]
hey, thank you for your fast reply!

yep, i did run that command. i just cleared the console for the screenshot. unfortunately i got the same error :/

**Comment by camwhi-te** [comment]
I'll have a look at this ASAP, seems like an infrequent yet very annoying issue. Thanks for reporting this!

**Comment by devilAPI** [comment]
thank you :)

**Comment by devilAPI** [comment]
https://github.com/pterodactyl/panel/commit/703f55271dc5dda9f023dbb1b98ab298ec323025

**Comment by devilAPI** [comment]
I fixed it by downloading the removed file `DaemonKeyRepositoryInterface.php`

`cd /var/www/pterodactyl/app/Contracts/Repository && wget https://raw.githubusercontent.com/pterodactyl/panel/4dddcaebb0423503a4b5437992f6da51afcc4870/app/Contracts/Repository/DaemonKeyRepositoryInterface.php`

**Comment by camwhi-te** [comment]
I'll add this file back, no clue in the world why it would have been deleted. Thanks for reporting this issue.
